version: "2"  # 2.x 和3.x的最大差異，2.x用於佈署單機、3.x用於佈署docker-swarm
services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - ./data/db:/data/db
  mongo-client:
    image: mongoclient/mongoclient
    ports:
    - 3030:3000
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo
  spring-boot-mongo-docker:
    image: adolphgirl/tomcatwar
    ports:
    - 8080:8080
    links:
    - mongo
        
